<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'SURVEY From Strengths Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'ANA.PENARANDA@CSUN.EDU',
		'to' => 'ANA.PENARANDA@CSUN.EDU,ampenaranda.design@gmail.com'
	),
	'fields' => array(
		'custom_U7965' => array(
			'order' => 10,
			'type' => 'string',
			'label' => '10. Explain how one of your Strengths themes impacts your relationships with other people',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'10. Explain how one of your Strengths themes impacts your relationships with other people\' is required.'
			)
		),
		'custom_U7977' => array(
			'order' => 11,
			'type' => 'string',
			'label' => '11. Explain how you can use one of your Strengths to achieve one of your career goals',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'11. Explain how you can use one of your Strengths to achieve one of your career goals\' is required.'
			)
		),
		'custom_U7989' => array(
			'order' => 12,
			'type' => 'string',
			'label' => '12. Explain a way in which you can use your Strengths toward academic success',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'12. Explain a way in which you can use your Strengths toward academic success\' is required.'
			)
		),
		'custom_U8199' => array(
			'order' => 15,
			'type' => 'string',
			'label' => '15. Any additional comments?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'15. Any additional comments?\' is required.'
			)
		),
		'custom_U7027' => array(
			'order' => 1,
			'type' => 'radiogroup',
			'label' => '1. Did you take the Strengths assessment?',
			'required' => true,
			'optionItems' => array(
				'Yes',
				' No (If NO, please stop here.)'
			),
			'errors' => array(
				'required' => 'Field \'1. Did you take the Strengths assessment?\' is required.',
				'format' => 'Field \'1. Did you take the Strengths assessment?\' has an invalid value.'
			)
		),
		'custom_U7713' => array(
			'order' => 7,
			'type' => 'radiogroup',
			'label' => '7. I feel like my Strengths results fit with my idea of myself',
			'required' => true,
			'optionItems' => array(
				'Strongly Agree',
				'Agree',
				'Neutral',
				'Disagree',
				'Strongly Disagree'
			),
			'errors' => array(
				'required' => 'Field \'7. I feel like my Strengths results fit with my idea of myself\' is required.',
				'format' => 'Field \'7. I feel like my Strengths results fit with my idea of myself\' has an invalid value.'
			)
		),
		'custom_U7303' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => '4. As a result of my Strengths assessment, I have a better understanding of how to use my talents and develop my Strengths to help me be successful',
			'required' => true,
			'optionItems' => array(
				'Strongly Agree',
				'Agree',
				'Neutral',
				'Disagree',
				'Strongly Disagree'
			),
			'errors' => array(
				'required' => 'Field \'4. As a result of my Strengths assessment, I have a better understanding of how to use my talents and develop my Strengths to help me be successful\' is required.',
				'format' => 'Field \'4. As a result of my Strengths assessment, I have a better understanding of how to use my talents and develop my Strengths to help me be successful\' has an invalid value.'
			)
		),
		'custom_U8001' => array(
			'order' => 13,
			'type' => 'radiogroup',
			'label' => '13. Please rate your overall impression of your Strengths experience',
			'required' => true,
			'optionItems' => array(
				'Excellent',
				'Good',
				'Fair',
				'Poor'
			),
			'errors' => array(
				'required' => 'Field \'13. Please rate your overall impression of your Strengths experience\' is required.',
				'format' => 'Field \'13. Please rate your overall impression of your Strengths experience\' has an invalid value.'
			)
		),
		'custom_U8085' => array(
			'order' => 14,
			'type' => 'radiogroup',
			'label' => '14. Please select your college of study',
			'required' => true,
			'optionItems' => array(
				' Arts, Media, & Communication',
				' Business & Economics',
				'Education',
				'Engineering & Computer Science',
				'Health & Human Development',
				'Humanities',
				'Science & Mathematics',
				'Social & Behavioral Sciences',
				'Undecided'
			),
			'errors' => array(
				'required' => 'Field \'14. Please select your college of study\' is required.',
				'format' => 'Field \'14. Please select your college of study\' has an invalid value.'
			)
		),
		'custom_U7608' => array(
			'order' => 6,
			'type' => 'checkboxgroup',
			'label' => '6. Career: Now that I know my talents and Strengths: (Check all that apply.)',
			'required' => true,
			'optionItems' => array(
				'I feel more motivated to achieve my career goals',
				'I have considered more career options',
				'I feel more confident about and prepared for planning my career',
				'I have not changed',
				'None of the above',
				'Other'
			),
			'errors' => array(
				'required' => 'Field \'6. Career: Now that I know my talents and Strengths: (Check all that apply.)\' is required.',
				'format' => 'Field \'6. Career: Now that I know my talents and Strengths: (Check all that apply.)\' has an invalid value.'
			)
		),
		'custom_U7797' => array(
			'order' => 8,
			'type' => 'radiogroup',
			'label' => '8. The Strengths assessment and website are engaging and interesting',
			'required' => true,
			'optionItems' => array(
				'Strongly Agree',
				'Agree',
				'Neutral',
				'Disagree',
				'Strongly Disagree'
			),
			'errors' => array(
				'required' => 'Field \'8. The Strengths assessment and website are engaging and interesting\' is required.',
				'format' => 'Field \'8. The Strengths assessment and website are engaging and interesting\' has an invalid value.'
			)
		),
		'custom_U7432' => array(
			'order' => 5,
			'type' => 'checkboxgroup',
			'label' => '5. Academics: Now that I know my talents and Strengths: (Check all that apply.)',
			'required' => true,
			'optionItems' => array(
				'I feel more motivated to achieve my academic goals',
				'I can think of specific ways to do well in my classes',
				'I feel more confident about and prepared for creating academic goals',
				'I am making better academic decisions',
				'I have not changed',
				'None of the above',
				'Other'
			),
			'errors' => array(
				'required' => 'Field \'5. Academics: Now that I know my talents and Strengths: (Check all that apply.)\' is required.',
				'format' => 'Field \'5. Academics: Now that I know my talents and Strengths: (Check all that apply.)\' has an invalid value.'
			)
		),
		'custom_U7101' => array(
			'order' => 2,
			'type' => 'radiogroup',
			'label' => '2. Have you spent time exploring and contemplating your Strengths results? (We recommend studying the definitions of your Top 5 Strengths and considering your dominant Strength domains before taking this survey.)',
			'required' => true,
			'optionItems' => array(
				'Yes',
				'No (If NO, please stop here.)'
			),
			'errors' => array(
				'required' => 'Field \'2. Have you spent time exploring and contemplating your Strengths results? (We recommend studying the definitions of your Top 5 Strengths and considering your dominant Strength domains before taking this survey.)\' is required.',
				'format' => 'Field \'2. Have you spent time exploring and contemplating your Strengths results? (We recommend studying the definitions of your Top 5 Strengths and considering your dominant Strength domains before taking this survey.)\' has an invalid value.'
			)
		),
		'custom_U7140' => array(
			'order' => 3,
			'type' => 'radiogroup',
			'label' => '3. Have you downloaded the templates for each of your Top 5 Strengths, and if so, did you find them informative and beneficial?',
			'required' => true,
			'optionItems' => array(
				'Yes',
				'No',
				'I did not download my templates'
			),
			'errors' => array(
				'required' => 'Field \'3. Have you downloaded the templates for each of your Top 5 Strengths, and if so, did you find them informative and beneficial?\' is required.',
				'format' => 'Field \'3. Have you downloaded the templates for each of your Top 5 Strengths, and if so, did you find them informative and beneficial?\' has an invalid value.'
			)
		),
		'custom_U7881' => array(
			'order' => 9,
			'type' => 'radiogroup',
			'label' => '9. Which features of the Strengths website did you find most helpful?',
			'required' => true,
			'optionItems' => array(
				'Information videos',
				'Engaging audio',
				'Colorful animations',
				'Comprehensive explanatory texts',
				'Interactive elements'
			),
			'errors' => array(
				'required' => 'Field \'9. Which features of the Strengths website did you find most helpful?\' is required.',
				'format' => 'Field \'9. Which features of the Strengths website did you find most helpful?\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
